### ISSUE TITLE
[Product Backlog] Add acceptance criteria to backlog

### ISSUE THREAD

**Issue by peerawutgaga** [we-inc/mms-full-stack-solo#75]

**Comment by nattapatboon** [comment]
Acceptance Criteria for Sprint1 has been added.

1) ผู้ใช้สามารถลงทะเบียนผ่าน Facebook account ได้

2) ผู้ใช้สามารถลงทะเบียนผ่าน Line account ได้

3) ผู้ใช้สามารถลงชื่อเข้าใช้ระบบผ่าน Facebook account ได้

4) ผู้ใช้สามารถลงชื่อเข้าใช้ระบบผ่าน Line account ได้
